### ISSUE TITLE
No popup menu shows up

### ISSUE THREAD

**Issue by caneta** [ncm2/ncm2-github#2]
I would like to view emoji popup menu as depicted in the gif inside readme file, but it does not show up.
I'm on Ubuntu Linux 14.04, with Neovim 0.3: are there any prerequisites to make it work?
Thanks

**Comment by caneta** [comment]
I noticed now that you have to write an .md file to get the menu shows up, sorry.
But is there a way to force it on any filetype?

**Comment by roxma** [comment]
This `github-emoji` source is defined in https://github.com/ncm2/ncm2-github/blob/master/autoload/ncm2_github.vim#L129

To force it on any filetype, you could use `call ncm2#override_source("github-emoji",  {"scope": []})`
